apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: hlltixdg7-python-gitops
  description: This is GitOps manifest for hlltixdg7-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=hlltixdg7-python
    backstage.io/kubernetes-id: hlltixdg7-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: hlltixdg7-python
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:hlltixdg7-python
